# Primary colors
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

# Cursor colors
[colors.cursor]
cursor = "#c0caf5"
text = "#1a1b26"

# Normal colors
[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#fedb32"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#00ffff"
white = "#a9b1d6"

# Bright colors
[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#00ffff"
white = "#c0caf5"

#| Posición | Nombre  | Suele usarse para                       |
#| -------- | ------- | --------------------------------------- |
#| 0        | black   | fondo alternativo / comentarios oscuros |
#| 1        | red     | errores                                 |
#| 2        | green   | éxito                                   |
#| 3        | yellow  | advertencias                            |
#| 4        | blue    | directorios                             |
#| 5        | magenta | valores especiales                      |
#| 6        | cyan    | enlaces / info                          |
#| 7        | white   | texto normal                            |
